# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Run Sender and Receiver

on:
  push:
    paths-ignore:
    - '**.md'
  pull_request:
    paths-ignore:
    - '**.md'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: pipe
      run:  ./testchecker | java -jar /home/runner/work/stream-bms-data-virendrasjhala/stream-bms-data-virendrasjhala/target/BatteryMgmtReceiver-0.0.1-SNAPSHOT.jar